### ISSUE TITLE
add powershell as dependency

### ISSUE THREAD

**Issue by nilslice** [dylibso/xtp-csharp-bindgen#9]
Unsure if `dotnet` would imply the existence of powershell tools, but may be worth adding here too.

https://github.com/dylibso/xtp-csharp-bindgen/blob/84129b70d1a2a12a1c56ae6ec50dc9efeda8437f/config.yaml#L3

**Comment by mhmd-azeez** [comment]
The only issue with that is, on Linux you can only install Powershell Core (`pwsh`), on windows, Powershell (`powershell`) is installed by default, but you can also install `pwsh`. I have changed the script to work with either of them. currently there is no way to specify this requirement: `pwsh` OR `powershell` in config.yaml
